# Memory settings for Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Loom 26.1+ unobfuscated mode
fabric.loom.disableObfuscation=true

# Mod Properties
mod_version=0.1.0-alpha.3
maven_group=se.jimmyeliasson.gzcompanion
archives_base_name=gzcompanion

# Tooling & Dependencies
minecraft_version=26.1.2
loader_version=0.19.5
fabric_version=0.155.3+26.1.2
loom_version=1.18.0-alpha.21
