#Requires -Version 5.1
<#
.SYNOPSIS
    Builds GZ-Companion-Setup.exe: the single-file, self-contained Windows installer for GZ Companion.

.DESCRIPTION
    0. Reads the ONE canonical product version from ..\..\gradle.properties (mod_version), hard-fails
       if distribution\compatibility.json's companionVersion disagrees with it, and regenerates
       GZCompanion.Installer.Core\GeneratedProductVersion.cs so the installer's own version can never
       independently drift from the mod's.
    1. Builds the GZ Companion mod jar via the main Gradle project (.\gradlew.bat build).
    2. Copies that jar into the installer's Assets folder as an embedded resource, and HARD-FAILS
       (does not produce an exe) if its SHA-256/size don't exactly match distribution\compatibility.json -
       an installer must never silently embed a jar its own manifest doesn't vouch for.
    3. Runs the installer's own test suite (dotnet test), which re-verifies the embedded jar's hash
       independently of this script.
    4. Publishes GZCompanion.Installer.App as a self-contained, single-file win-x64 executable -
       the end user needs no .NET runtime, no Java, nothing beyond Windows itself.
    5. Copies the published exe to distribution\dist\GZ-Companion-Setup.exe and prints its SHA-256.

    Run from anywhere; paths are resolved relative to this script's own location.
#>
param(
    [switch]$SkipModBuild,
    [switch]$SkipTests
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir "..\..")
$distributionDir = Join-Path $repoRoot "distribution"
$installerDir = $scriptDir
$appProject = Join-Path $installerDir "GZCompanion.Installer.App\GZCompanion.Installer.App.csproj"
$testsProject = Join-Path $installerDir "GZCompanion.Installer.Tests\GZCompanion.Installer.Tests.csproj"
$assetsDir = Join-Path $installerDir "GZCompanion.Installer.App\Assets"
$distDir = Join-Path $distributionDir "dist"
$generatedVersionFile = Join-Path $installerDir "GZCompanion.Installer.Core\GeneratedProductVersion.cs"

Write-Host "== 0. Verifying canonical version ==" -ForegroundColor Cyan
$gradlePropsPath = Join-Path $repoRoot "gradle.properties"
$modVersionLine = Get-Content $gradlePropsPath | Where-Object { $_ -match '^\s*mod_version\s*=' } | Select-Object -First 1
if (-not $modVersionLine) { throw "Could not find mod_version= in $gradlePropsPath" }
$canonicalVersion = ($modVersionLine -split '=', 2)[1].Trim()
Write-Host "Canonical version (gradle.properties mod_version): $canonicalVersion"

$compatManifestVersion = (Get-Content (Join-Path $distributionDir "compatibility.json") -Raw | ConvertFrom-Json).supported[0].companionVersion
if ($compatManifestVersion -ne $canonicalVersion) {
    Write-Host ""
    Write-Host "BUILD FAILED: version mismatch." -ForegroundColor Red
    Write-Host "  gradle.properties mod_version       = $canonicalVersion" -ForegroundColor Red
    Write-Host "  compatibility.json companionVersion  = $compatManifestVersion" -ForegroundColor Red
    Write-Host "Bump BOTH to the same version before building a release. See distribution\RELEASING.md." -ForegroundColor Red
    exit 1
}

Set-Content -Path $generatedVersionFile -Encoding utf8 -Value @"
namespace GZCompanion.Installer.Core;

/// <summary>
/// The installer's single canonical product version - regenerated at build time by
/// distribution/installer/build-installer.ps1 from this repository's own single source of truth,
/// gradle.properties' mod_version. Do not edit this file by hand; your edit will be silently
/// overwritten on the next build. See distribution/RELEASING.md.
/// </summary>
public static class GeneratedProductVersion
{
    public const string Value = "$canonicalVersion";
}
"@
Write-Host "Generated GeneratedProductVersion.cs with version $canonicalVersion." -ForegroundColor Green

Write-Host "== 1. Building GZ Companion mod jar ==" -ForegroundColor Cyan
if (-not $SkipModBuild) {
    Push-Location $repoRoot
    try {
        & ".\gradlew.bat" build --console=plain
        if ($LASTEXITCODE -ne 0) { throw "gradlew.bat build failed with exit code $LASTEXITCODE" }
    } finally {
        Pop-Location
    }
} else {
    Write-Host "Skipped (-SkipModBuild)." -ForegroundColor Yellow
}

$modJar = Get-ChildItem (Join-Path $repoRoot "build\libs") -Filter "gzcompanion-*.jar" |
    Where-Object { $_.Name -notlike "*-sources.jar" } |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1
if (-not $modJar) { throw "Could not find a built gzcompanion-*.jar under build\libs. Run .\gradlew.bat build first." }
Write-Host "Using mod jar: $($modJar.FullName)"

Write-Host "== 2. Embedding mod jar into installer Assets ==" -ForegroundColor Cyan
New-Item -ItemType Directory -Force -Path $assetsDir | Out-Null
Copy-Item $modJar.FullName (Join-Path $assetsDir "gzcompanion.jar") -Force

$modJarHash = (Get-FileHash $modJar.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
$modJarSize = (Get-Item $modJar.FullName).Length
$manifest = (Get-Content (Join-Path $distributionDir "compatibility.json") -Raw | ConvertFrom-Json).supported[0].companionJar
Write-Host "Freshly built mod jar: sha256=$modJarHash size=$modJarSize"
Write-Host "compatibility.json expects: sha256=$($manifest.sha256) size=$($manifest.sizeBytes)"

if ($modJarHash -ne $manifest.sha256 -or $modJarSize -ne $manifest.sizeBytes) {
    Remove-Item (Join-Path $assetsDir "gzcompanion.jar") -Force -ErrorAction SilentlyContinue
    Write-Host ""
    Write-Host "BUILD FAILED: embedded jar does not match distribution\compatibility.json." -ForegroundColor Red
    if ($modJarHash -ne $manifest.sha256) {
        Write-Host "  sha256 mismatch: built=$modJarHash  manifest=$($manifest.sha256)" -ForegroundColor Red
    }
    if ($modJarSize -ne $manifest.sizeBytes) {
        Write-Host "  size mismatch:   built=$modJarSize  manifest=$($manifest.sizeBytes)" -ForegroundColor Red
    }
    Write-Host "GZ-Companion-Setup.exe was NOT produced. If this mod change is intentional, update" -ForegroundColor Red
    Write-Host "distribution\compatibility.json's companionJar.sha256/sizeBytes to match, then re-run." -ForegroundColor Red
    exit 1
}
if ($modJar.Name -ne $manifest.fileName) {
    Write-Host ""
    Write-Host "BUILD FAILED: built jar filename does not match compatibility.json." -ForegroundColor Red
    Write-Host "  built=$($modJar.Name)  manifest=$($manifest.fileName)" -ForegroundColor Red
    exit 1
}
Write-Host "Embedded jar verified against compatibility.json." -ForegroundColor Green

Write-Host "== 3. Running installer test suite ==" -ForegroundColor Cyan
if (-not $SkipTests) {
    dotnet test $testsProject -c Release
    if ($LASTEXITCODE -ne 0) {
        Write-Host ""
        Write-Host "BUILD FAILED: installer test suite did not pass. GZ-Companion-Setup.exe was NOT produced." -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host "Skipped (-SkipTests)." -ForegroundColor Yellow
}

Write-Host "== 4. Publishing self-contained single-file installer ==" -ForegroundColor Cyan
$publishDir = Join-Path $installerDir "GZCompanion.Installer.App\bin\Release\net10.0-windows\win-x64\publish"
dotnet publish $appProject -c Release -r win-x64 --self-contained true `
    -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:EnableCompressionInSingleFile=true
if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed with exit code $LASTEXITCODE" }

Write-Host "== 5. Copying final installer to distribution\dist ==" -ForegroundColor Cyan
New-Item -ItemType Directory -Force -Path $distDir | Out-Null
$finalExe = Join-Path $distDir "GZ-Companion-Setup.exe"
Copy-Item (Join-Path $publishDir "GZ-Companion-Setup.exe") $finalExe -Force

$hash = (Get-FileHash $finalExe -Algorithm SHA256).Hash.ToLowerInvariant()
$size = (Get-Item $finalExe).Length
Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host "  Path:   $finalExe"
Write-Host "  Size:   $size bytes"
Write-Host "  SHA256: $hash"
