namespace GZCompanion.Installer.Core;

/// <summary>
/// The installer's single canonical product version - regenerated at build time by
/// distribution/installer/build-installer.ps1 from this repository's own single source of truth,
/// gradle.properties' mod_version. Do not edit this file by hand; your edit will be silently
/// overwritten on the next build. See distribution/RELEASING.md.
/// </summary>
public static class GeneratedProductVersion
{
    public const string Value = "0.1.0-alpha.2";
}
