<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GZCompanion.Installer.Core</RootNamespace>
    <AssemblyName>GZCompanion.Installer.Core</AssemblyName>
  </PropertyGroup>

</Project>
